bump_version: null
lint:
  actions_ci: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-exomecnv_logo_light.png
    - docs/images/nf-core-exomecnv_logo_light.png
    - docs/images/nf-core-exomecnv_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-exomecnv_logo_light.png
    - docs/images/nf-core-exomecnv_logo_light.png
    - docs/images/nf-core-exomecnv_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .gitignore
    - .github/workflows/branch.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: nvnieuwk
  description: A nextflow pipeline for calling exome CNVs
  force: false
  is_nfcore: false
  name: exomecnv
  org: nf-cmgg
  outdir: .
  skip_features: null
  version: 1.1.0
update: null
